import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? "file:./data/app.db",
});
const prisma = new PrismaClient({ adapter });

type SeedQuestion = {
  topicSlug: string;
  kind: "mc" | "open";
  stemCs: string;
  choices?: string[];
  correctAnswer: string;
  explanationCs: string;
  sourceRef: string;
};

const topics = [
  { slug: "anatomie", nameCs: "Anatomie a fyziologie", weight: 1.2 },
  { slug: "kontraindikace-a-kuze", nameCs: "Kontraindikace a kůže", weight: 1.3 },
  { slug: "komunikace-s-klientem", nameCs: "Komunikace s klientem", weight: 1.0 },
  { slug: "dokumentace-a-gdpr", nameCs: "Dokumentace a GDPR", weight: 1.0 },
  { slug: "hygiena-a-dezinfekce", nameCs: "Hygiena a dezinfekce", weight: 1.2 },
  { slug: "provozni-standardy", nameCs: "Provozní standardy a KHS", weight: 1.1 },
];

const NSK_ANATOMIE = "NSK 69-037-M § Doména 2 – Fyzické posouzení (docs/sources/NSK-69-037-M-hodnotici-standard.md)";
const NSK_KONTRA = "NSK 69-037-M § Doména 2.5 – Kůže a kontraindikace (docs/sources/NSK-69-037-M-hodnotici-standard.md)";
const NSK_KOMUNIKACE = "NSK 69-037-M § Doména 1 – Komunikace s klientem a řízení objednávek (docs/sources/NSK-69-037-M-hodnotici-standard.md)";
const NSK_HYGIENA = "NSK 69-037-M § Doména 3 – Hygiena a zdravotní soulad (docs/sources/NSK-69-037-M-hodnotici-standard.md)";
const GDPR = "Nařízení EU 2016/679 (GDPR) (docs/sources/legislation-summary.md)";
const ZAKON_258 = "Zákon č. 258/2000 Sb. § 19–22 o ochraně veřejného zdraví (docs/sources/legislation-summary.md)";
const VYHL_306 = "Vyhláška č. 306/2012 Sb. o hygienických požadavcích (docs/sources/legislation-summary.md)";
const CURRICULUM = "docs/curriculum.md § 2 Physical Assessment";
const CURRICULUM_D1 = "docs/curriculum.md § 1 Client Communication & Booking Management";
const CURRICULUM_D3 = "docs/curriculum.md § 3 Health & Hygiene Compliance";

const questions: SeedQuestion[] = [
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Kolik kostí tvoří průměrnou kostru dospělého člověka?",
    choices: ["186", "206", "226", "246"],
    correctAnswer: "206",
    explanationCs: "Dospělý člověk má přibližně 206 kostí. Novorozenec jich má více (některé během růstu srůstají, např. kosti lebky a křížová kost).",
    sourceRef: `${NSK_ANATOMIE} § 2.1 Kostra`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Která z následujících kostí patří mezi kosti dlouhé?",
    choices: ["Kost klínová", "Obratel", "Stehenní kost (femur)", "Čéška (patella)"],
    correctAnswer: "Stehenní kost (femur)",
    explanationCs: "Dlouhé kosti mají tělo (diafýzu) a dvě rozšířené konce (epifýzy). Typickými příklady jsou femur, humerus, tibia, fibula. Patella je kost sezamská, obratel patří mezi kosti nepravidelné.",
    sourceRef: `${NSK_ANATOMIE} § 2.1 Kostra`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Ramenní kloub je z hlediska tvaru kloubních ploch kloubem:",
    choices: ["Pantovým", "Kulovým", "Sedlovým", "Plochým"],
    correctAnswer: "Kulovým",
    explanationCs: "Ramenní kloub (articulatio humeri) je kulový volný kloub – umožňuje pohyb ve všech třech osách (flexe/extenze, abdukce/addukce, rotace).",
    sourceRef: `${NSK_ANATOMIE} § 2.1 Kostra`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Loketní kloub mezi humerem a ulnou je kloubem:",
    choices: ["Kulovým", "Pantovým", "Sedlovým", "Kondylárním"],
    correctAnswer: "Pantovým",
    explanationCs: "Mezi humerem a ulnou je pantový (válcový) kloub umožňující pouze flexi a extenzi v jedné ose. Rotaci předloktí (pronaci/supinaci) zajišťuje radioulnární kloub.",
    sourceRef: `${NSK_ANATOMIE} § 2.1 Kostra`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Která kost je nejdelší a nejsilnější kostí lidského těla?",
    choices: ["Pažní kost (humerus)", "Holenní kost (tibia)", "Pánevní kost", "Stehenní kost (femur)"],
    correctAnswer: "Stehenní kost (femur)",
    explanationCs: "Femur je nejdelší, nejsilnější a nejtěžší kost lidského těla. Nese hlavní zatížení při stoji a chůzi.",
    sourceRef: `${NSK_ANATOMIE} § 2.1 Kostra`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Sval m. trapezius (trapézový sval) působí především na:",
    choices: ["Loketní kloub", "Zápěstí", "Lopatku a krční páteř", "Kolenní kloub"],
    correctAnswer: "Lopatku a krční páteř",
    explanationCs: "M. trapezius pohybuje lopatkou (elevace, deprese, retrakce, rotace) a podílí se na extenzi a úklonu krční páteře. Je klíčový pro postýrů a masáž horní části zad.",
    sourceRef: `${NSK_ANATOMIE} § 2.2 Svalová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Hlavní funkcí m. biceps brachii je:",
    choices: ["Extenze lokte", "Flexe lokte a supinace předloktí", "Abdukce ramene", "Rotace hlavy"],
    correctAnswer: "Flexe lokte a supinace předloktí",
    explanationCs: "M. biceps brachii je dvouhlavý sval pažní – ohýbá v lokti a zároveň supinuje (otáčí dlaní nahoru) předloktí. Antagonistou je m. triceps brachii.",
    sourceRef: `${NSK_ANATOMIE} § 2.2 Svalová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Kosterní sval je řízen:",
    choices: ["Autonomním nervovým systémem", "Pouze hormonálně", "Volní (somatickou) kontrolou", "Jen míšními reflexy"],
    correctAnswer: "Volní (somatickou) kontrolou",
    explanationCs: "Kosterní sval je pod volní kontrolou somatického nervového systému (na rozdíl od hladkého svalstva a srdečního svalstva, které řídí autonomní systém).",
    sourceRef: `${NSK_ANATOMIE} § 2.2 Svalová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Pojmem „origo“ (začátek) svalu se rozumí:",
    choices: ["Místo úponu na pohyblivější kosti", "Pevnější začátek svalu na méně pohyblivé kosti", "Prostřední část svalu", "Šlachovité zakončení"],
    correctAnswer: "Pevnější začátek svalu na méně pohyblivé kosti",
    explanationCs: "Origo je proximální, obvykle pevnější začátek svalu; insertio (úpon) je distální konec, který se při kontrakci přibližuje k origu. Rozlišení pomáhá určit funkci svalu.",
    sourceRef: `${NSK_ANATOMIE} § 2.2 Svalová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Izometrická kontrakce je taková, při které sval:",
    choices: ["Se zkracuje a pohybuje kloubem", "Se prodlužuje pod zátěží", "Vyvíjí napětí bez změny délky", "Ztrácí napětí úplně"],
    correctAnswer: "Vyvíjí napětí bez změny délky",
    explanationCs: "Při izometrické kontrakci se mění svalové napětí, ale nemění se délka svalu (např. držení břemene v klidu). Izotonická kontrakce mění délku při zachování napětí.",
    sourceRef: `${NSK_ANATOMIE} § 2.2 Svalová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Hlavním nádechovým svalem je:",
    choices: ["Bránice (diafragma)", "M. rectus abdominis", "M. pectoralis minor", "Mezižeberní svaly vnější jen"],
    correctAnswer: "Bránice (diafragma)",
    explanationCs: "Bránice je hlavní inspirační sval; její kontrakce snižuje klenbu a zvětšuje objem hrudníku, čímž dochází k nádechu. Mezižeberní svaly jsou pomocné.",
    sourceRef: `${NSK_ANATOMIE} § 2.3 Dýchací soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Výměna plynů (O₂ a CO₂) mezi vzduchem a krví probíhá v:",
    choices: ["Průdušnici (trachea)", "Velkých bronších", "Plicních sklípcích (alveolech)", "Pohrudnici"],
    correctAnswer: "Plicních sklípcích (alveolech)",
    explanationCs: "V plicních alveolech je tenká stěna (jedna vrstva buněk) a bohatá kapilární síť – ideální pro difuzi plynů. Trachea a bronchy jsou pouze vedení vzduchu.",
    sourceRef: `${NSK_ANATOMIE} § 2.3 Dýchací soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Tepny (arterie) vedou krev:",
    choices: ["Vždy k srdci", "Vždy od srdce", "Jen v plicním oběhu", "Jen v systémovém oběhu"],
    correctAnswer: "Vždy od srdce",
    explanationCs: "Definice: tepny vedou krev od srdce (bez ohledu na obsah kyslíku). V plicním oběhu tedy tepny (plicnice) nesou odkysličenou krev, v systémovém oběhu okysličenou.",
    sourceRef: `${NSK_ANATOMIE} § 2.4 Oběhová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Mízní (lymfatické) uzliny jsou součástí:",
    choices: ["Nervového systému", "Endokrinního systému", "Lymfatického (imunitního) systému", "Trávicího systému"],
    correctAnswer: "Lymfatického (imunitního) systému",
    explanationCs: "Mízní uzliny filtrují lymfu a účastní se imunitní reakce. Při masáži se vyhýbáme tlaku přímo na uzliny a respektujeme směr odtoku lymfy k centrálním uzlinám.",
    sourceRef: `${NSK_ANATOMIE} § 2.4 Oběhová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "mc",
    stemCs: "Při klasické masáži končetin směřují hlavní tahy převážně:",
    choices: ["Od srdce k periferii (proti směru žilního návratu)", "Od periferie k srdci (ve směru žilního návratu)", "Vždy od hlavy k patě", "Libovolně, směr nehraje roli"],
    correctAnswer: "Od periferie k srdci (ve směru žilního návratu)",
    explanationCs: "Masáž podporuje žilní a lymfatický návrat, proto dlouhé tahy (effleurage) vedeme od periferie (distálně) směrem k srdci (proximálně). Opačný směr by zatěžoval chlopně žil.",
    sourceRef: `${NSK_ANATOMIE} § 2.4 Oběhová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "open",
    stemCs: "Vyjmenujte tři základní typy synoviálních kloubů podle tvaru kloubních ploch a ke každému uveďte anatomický příklad.",
    correctAnswer: "Kulový kloub (např. ramenní, kyčelní); pantový/válcový kloub (např. loketní, mezičlánkové klouby prstů); sedlový kloub (např. karpometakarpální kloub palce ruky). Další přijatelné: kondylární (kolenní), plochý (meziobratlové), čepový (atlanto-axiální).",
    explanationCs: "Tvar kloubních ploch určuje rozsah a osy pohybu. Kulové klouby mají tři stupně volnosti, pantové jeden, sedlové dva. Znalost je důležitá pro volbu masážní techniky a mobilizace.",
    sourceRef: `${NSK_ANATOMIE} § 2.1 Kostra`,
  },
  {
    topicSlug: "anatomie",
    kind: "open",
    stemCs: "Popište dráhu malého (plicního) krevního oběhu od pravé komory po levou síň.",
    correctAnswer: "Pravá komora → plicnice (truncus pulmonalis) → pravá a levá plicní tepna → plicní kapiláry v alveolech (výměna plynů) → plicní žíly → levá síň.",
    explanationCs: "Malý oběh slouží k okysličení krve. Znalost je důležitá pro pochopení kontraindikací u plicní hypertenze a edému plic.",
    sourceRef: `${NSK_ANATOMIE} § 2.3-2.4 Dýchací a oběhová soustava`,
  },
  {
    topicSlug: "anatomie",
    kind: "open",
    stemCs: "Vysvětlete pojmy „origo“ a „insertio“ u kosterního svalu a uveďte, proč je toto rozlišení důležité pro maséra.",
    correctAnswer: "Origo je pevnější, obvykle proximální začátek svalu na méně pohyblivé kosti. Insertio je distální úpon na pohyblivější kosti, která se při kontrakci přibližuje k origu. Pro maséra je rozlišení důležité proto, aby věděl směr průběhu svalových vláken, funkci svalu (jaký pohyb vyvolává), a tím volil směr a techniku hnětení po průběhu svalu od origa k insertiu.",
    explanationCs: "Bez znalosti origa a insertia nelze správně nahmatat svalové bříško ani určit, který pohyb sval vyvolává (důležité např. při triggerpoint terapii).",
    sourceRef: `${NSK_ANATOMIE} § 2.2 Svalová soustava`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "mc",
    stemCs: "Mezi absolutní (celkové) kontraindikace masáže patří:",
    choices: ["Mírná únava po cvičení", "Akutní horečnaté onemocnění", "Svalová ztuhlost druhý den po tréninku", "Suchá pokožka v zimě"],
    correctAnswer: "Akutní horečnaté onemocnění",
    explanationCs: "Horečka nad 37,5 °C a akutní infekce jsou absolutní kontraindikací – masáž by zatížila oběh, rozšířila infekci a zhoršila stav. Po odeznění a 48 h bez teploty lze masírovat.",
    sourceRef: `${NSK_KONTRA}`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "mc",
    stemCs: "V oblasti akutního zánětu nebo lokální infekce masér:",
    choices: ["Masíruje s vyšším tlakem pro prokrvení", "Oblasti se musí zcela vyhnout", "Masíruje pouze jemnou effleurage", "Aplikuje teplo a poté masáž"],
    correctAnswer: "Oblasti se musí zcela vyhnout",
    explanationCs: "Masáž akutně zanícené či infikované tkáně hrozí šířením zánětu nebo infekce (lymfou a krevním řečištěm) a zhoršením stavu. Oblast se vynechává; klient jde k lékaři.",
    sourceRef: `${NSK_KONTRA}`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "mc",
    stemCs: "Svrchní vrstvu kůže (epidermis) tvoří především:",
    choices: ["Tukové buňky (adipocyty)", "Svalová vlákna", "Dlaždicový epitel s keratinocyty", "Pouze nervová zakončení"],
    correctAnswer: "Dlaždicový epitel s keratinocyty",
    explanationCs: "Epidermis je mnohovrstevnatý dlaždicový rohovatějící epitel. Hlavní buněčný typ jsou keratinocyty; dále melanocyty, Langerhansovy a Merkelovy buňky.",
    sourceRef: `${NSK_KONTRA} § Kůže`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "mc",
    stemCs: "Podezření na hlubokou žilní trombózu (DVT) v dolní končetině znamená:",
    choices: ["Indikaci k hluboké masáži lýtka pro rozpuštění trombu", "Absolutní kontraindikaci masáže končetiny a akutní doporučení lékařského vyšetření", "Masáž pouze ve směru od srdce", "Zvýšený tlak na bérec"],
    correctAnswer: "Absolutní kontraindikaci masáže končetiny a akutní doporučení lékařského vyšetření",
    explanationCs: "Masáž při DVT může uvolnit trombus a způsobit plicní embolii – život ohrožující stav. Příznaky: jednostranný otok, bolest lýtka, teplo, zarudnutí. Klient k lékaři.",
    sourceRef: `${NSK_KONTRA}`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "mc",
    stemCs: "Mezi infekční kožní onemocnění, která vylučují masáž dané oblasti, patří:",
    choices: ["Suchá kůže", "Stará jizva z dětství", "Plísňová infekce (tinea, mykóza)", "Vrozené pigmentové znaménko"],
    correctAnswer: "Plísňová infekce (tinea, mykóza)",
    explanationCs: "Plísňové, bakteriální i virové kožní infekce se masáží přenášejí na maséra i na další části těla klienta. Oblast se vynechává a doporučuje se dermatologické ošetření.",
    sourceRef: `${NSK_KONTRA}`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "open",
    stemCs: "Uveďte pět (5) stavů, při kterých masáž NESMÍ být provedena (absolutní kontraindikace), a ke každému stručně odůvodněte.",
    correctAnswer: "Příklady (stačí jakýchkoliv 5): 1) Horečka / akutní infekce – riziko zhoršení stavu a přenosu. 2) Hluboká žilní trombóza – riziko embolie. 3) Akutní úraz, zlomenina, čerstvá operace – riziko krvácení a zhoršení hojení. 4) Otevřené rány, ekzém v akutní fázi, infekční kožní choroby – riziko kontaminace. 5) Neléčené nádorové onemocnění – možné šíření. 6) Těžká nekompenzovaná hypertenze nebo srdeční nedostatečnost – oběhové zhoršení. 7) Silná intoxikace (alkohol, drogy) – nespolupracující klient. 8) Krvácivé stavy / antikoagulační léčba v toxické dávce – riziko hematomů.",
    explanationCs: "Seznam absolutních kontraindikací je podmnožinou standardu. Relativní kontraindikace (těhotenství, diabetes, hypertenze kompenzovaná) vyžadují souhlas lékaře a úpravu techniky.",
    sourceRef: `${NSK_KONTRA}; ${CURRICULUM}`,
  },
  {
    topicSlug: "kontraindikace-a-kuze",
    kind: "open",
    stemCs: "Proč jsou křečové žíly (varixy) lokální kontraindikací? Popište, jak postupovat při masáži klienta, který má varixy pouze na bércích.",
    correctAnswer: "Varixy jsou rozšířené, chronicky poškozené povrchové žíly s nedomykavými chlopněmi; tlak na ně může poškodit křehkou cévní stěnu, způsobit hematom nebo odtržení trombu z povrchového systému. Postup: postiženému úseku (konkrétní varixy) se masér zcela vyhne, na okolí (stehno, chodidlo) použije pouze jemné tahy ve směru žilního návratu (distálně → proximálně) a zcela vynechá hnětení, tapotement a kompresi na bércích s varixy. Klienta upozorní na ošetření žil flebologem.",
    explanationCs: "Rozlišujeme lokální kontraindikaci (masáž vynechá pouze daný úsek) a celkovou (masáž se neprovádí vůbec). Varixy jsou typicky lokální; pokud jsou rozsáhlé nebo doprovází chronickou žilní insuficienci s otokem, masáž odmítáme zcela a odesíláme k lékaři.",
    sourceRef: `${NSK_KONTRA}`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Při telefonickém objednávání nového klienta by měl masér standardně:",
    choices: [
      "Pouze zapsat jméno a čas",
      "Ověřit cíl návštěvy, stručně se zeptat na zdravotní stav a sdělit délku, cenu a storno podmínky",
      "Požadovat zaslání zdravotní dokumentace od praktického lékaře",
      "Odmítnout dotaz na zdravotní stav jako nevhodný",
    ],
    correctAnswer: "Ověřit cíl návštěvy, stručně se zeptat na zdravotní stav a sdělit délku, cenu a storno podmínky",
    explanationCs: "Krátký pretriáž při objednání (cíl, případné kontraindikace) umožní předem vyloučit, že klient přijde zbytečně. Transparentní informace o ceně, délce a storno podmínkách jsou povinnou součástí informace o službě podle zákona o ochraně spotřebitele.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.1 Objednávání klienta`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Klient zruší rezervaci 2 hodiny před termínem. Masér má na webu uvedenu storno lhůtu 24 h. Jaký postup je korektní?",
    choices: [
      "Nárok na storno poplatek vzniká, protože lhůta byla klientovi předem transparentně sdělena",
      "Storno nelze účtovat, lhůta nemá oporu v zákoně",
      "Lze účtovat jen plnou cenu služby",
      "Storno poplatek je zakázán občanským zákoníkem",
    ],
    correctAnswer: "Nárok na storno poplatek vzniká, protože lhůta byla klientovi předem transparentně sdělena",
    explanationCs: "Předem sjednané a klientovi sdělené storno podmínky jsou součástí smlouvy o službě. Výše storna musí být přiměřená (typicky 50–100 % ceny dle jak blízko k termínu). Nutné je, aby byly dostupné před rezervací (web, e-mail, provozní řád).",
    sourceRef: `${NSK_KOMUNIKACE} § 1.1 Objednávání klienta; Zákon 89/2012 Sb. § 1811 (informační povinnost)`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Hlavním účelem vstupního dotazníku (intake/anamnéza) před první masáží je:",
    choices: [
      "Zjistit preferovanou hudbu a teplotu v místnosti",
      "Získat marketingová data o klientovi",
      "Identifikovat kontraindikace, zdravotní rizika a přizpůsobit techniku stavu klienta",
      "Splnit formalitu pro účetnictví",
    ],
    correctAnswer: "Identifikovat kontraindikace, zdravotní rizika a přizpůsobit techniku stavu klienta",
    explanationCs: "Intake má především bezpečnostní funkci – masér se dozví o úrazech, onemocněních, lécích a těhotenství, aby mohl vyloučit absolutní kontraindikace a upravit masáž. Zároveň slouží jako doklad o due diligence pro případ pojistné události.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.2 Zdravotní anamnéza a příjem klienta`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Klient v dotazníku uvede, že užívá warfarin (antikoagulancium). Masér by měl:",
    choices: [
      "Masáž zcela odmítnout",
      "Provést běžnou masáž bez úprav – lék nemá vliv",
      "Vynechat hluboké a intenzivní techniky, omezit tapotement a silnější hnětení kvůli riziku hematomů; konzultovat rozsah s klientem/lékařem",
      "Použít naopak silnější tlak pro lepší prokrvení",
    ],
    correctAnswer: "Vynechat hluboké a intenzivní techniky, omezit tapotement a silnější hnětení kvůli riziku hematomů; konzultovat rozsah s klientem/lékařem",
    explanationCs: "Antikoagulancia zvyšují riziko krvácení a podkožních hematomů. Jemná relaxační masáž je obvykle možná; silný tlak, tapotement, hluboká friktura a bankování jsou kontraindikovány. U nově nasazené léčby se vyplatí písemná konzultace s ošetřujícím lékařem.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.2 Zdravotní anamnéza`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Informovaný souhlas klienta s masáží by měl obsahovat především:",
    choices: [
      "Pouze jméno klienta a datum",
      "Popis zákroku, očekávaný průběh, rizika, kontraindikace a právo souhlas kdykoliv odvolat",
      "Slib, že masáž vyléčí uvedené obtíže",
      "Potvrzení, že masér nenese žádnou odpovědnost za újmu",
    ],
    correctAnswer: "Popis zákroku, očekávaný průběh, rizika, kontraindikace a právo souhlas kdykoliv odvolat",
    explanationCs: "Informovaný souhlas musí být svobodný, konkrétní, informovaný a jednoznačný (GDPR čl. 4 bod 11, občanský zákoník § 93). Vzdání se odpovědnosti za způsobenou škodu nelze sjednat dopředu (§ 2898 OZ).",
    sourceRef: `${NSK_KOMUNIKACE} § 1.2; Zákon 89/2012 Sb. § 93, § 2898`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Aktivní naslouchání při rozhovoru s klientem znamená:",
    choices: [
      "Mlčet a nereagovat, dokud klient nedomluví",
      "Soustředěná pozornost, parafráze obsahu, otevřené otázky a ověření porozumění",
      "Průběžně radit řešení z vlastní zkušenosti",
      "Dělat si podrobné poznámky do notebooku během hovoru",
    ],
    correctAnswer: "Soustředěná pozornost, parafráze obsahu, otevřené otázky a ověření porozumění",
    explanationCs: "Aktivní naslouchání (dle Rogerse) zahrnuje pozorné vnímání, zrcadlení obsahu i emocí, otevřené otázky (co, jak) a shrnutí na závěr („Rozumím tomu dobře, že…?“). Odlišuje se od pasivního mlčení i od předčasného radění.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.3 Komunikační protokoly`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Klient se ptá, zda masáž vyléčí jeho chronickou bolest zad. Nejvhodnější odpověď:",
    choices: [
      "Ano, masáž bolest zad vyléčí",
      "Nevím, zkusíme to",
      "Masáž může přinést úlevu od napětí a doplnit rehabilitaci, ale nenahrazuje lékařskou diagnózu – doporučuji konzultaci s lékařem",
      "Masáž nic nedokáže, jděte rovnou na operaci",
    ],
    correctAnswer: "Masáž může přinést úlevu od napětí a doplnit rehabilitaci, ale nenahrazuje lékařskou diagnózu – doporučuji konzultaci s lékařem",
    explanationCs: "Masér není zdravotnický pracovník a nesmí diagnostikovat ani slibovat léčebný efekt. Realistické vysvětlení přínosů (úleva od napětí, relaxace) a hranic (nenahrazuje lékařskou péči) je zároveň eticky správné a právně bezpečné.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.3; Zákon 372/2011 Sb. (kdo smí léčit)`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Při komunikaci se starším klientem se sníženým sluchem je vhodné:",
    choices: [
      "Mluvit výrazně nahlas a křičet",
      "Mluvit čelem ke klientovi, pomaleji a zřetelně, ověřit porozumění, nabídnout písemnou variantu",
      "Nechat rozhovor na doprovodu klienta",
      "Psát všechno SMS zprávou",
    ],
    correctAnswer: "Mluvit čelem ke klientovi, pomaleji a zřetelně, ověřit porozumění, nabídnout písemnou variantu",
    explanationCs: "Křik zkresluje souhlásky a je nepříjemný. Seniorovi pomáhá možnost odezírat, snížená rychlost řeči, klidné prostředí a písemný doplněk. Důstojnost klienta má přednost před efektivitou.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.4 Speciální populace`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "U klienta s historií úzkosti nebo traumatu je vhodné:",
    choices: [
      "Ignorovat a masírovat standardně, aby si klient zvykl",
      "Masírovat bez dotýkání se těla",
      "Každý krok vysvětlit předem, dohodnout stop-signál, dát klientovi možnost kontroly nad tempem a polohou",
      "Použít hluboké techniky pro rychlé uvolnění",
    ],
    correctAnswer: "Každý krok vysvětlit předem, dohodnout stop-signál, dát klientovi možnost kontroly nad tempem a polohou",
    explanationCs: "Trauma-informed přístup (SAMHSA): bezpečí, transparentnost, volba, spolupráce. Předvídatelnost snižuje úzkost; stop-signál vrací klientovi kontrolu. Nevhodné jsou rychlé, neohlášené doteky na citlivých oblastech (krk, zadní strana stehen).",
    sourceRef: `${NSK_KOMUNIKACE} § 1.4 Speciální populace`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Klient nemluví plynně česky a masér nezná jeho jazyk. Nejvhodnější postup:",
    choices: [
      "Odmítnout ošetření, protože není možná komunikace",
      "Použít jednoduchý jazyk, ukazovat na tělo, případně překladač, a získat informovaný souhlas v jazyce, kterému klient rozumí",
      "Masírovat beze slov a nechat jazykový aspekt stranou",
      "Požádat doprovod, aby během masáže překládal bez souhlasu klienta",
    ],
    correctAnswer: "Použít jednoduchý jazyk, ukazovat na tělo, případně překladač, a získat informovaný souhlas v jazyce, kterému klient rozumí",
    explanationCs: "Informovaný souhlas vyžaduje porozumění; klient musí rozumět popisu, rizikům a storno politice. Strojový překladač je přijatelný pro běžné situace; u složitých zdravotních stavů je vhodné získat pomoc důvěryhodného překladatele (se souhlasem klienta kvůli GDPR).",
    sourceRef: `${NSK_KOMUNIKACE} § 1.4 Speciální populace; ${GDPR} čl. 7`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Neverbální signály klienta během masáže (napětí svalu, zatajený dech, ucuknutí) by měly vést maséra k:",
    choices: [
      "Pokračování stejnou intenzitou, klient si musí zvyknout",
      "Okamžitému ukončení celé masáže",
      "Snížení tlaku / přerušení techniky a slovnímu ověření komfortu a intenzity",
      "Ignorování – klient si řekne sám",
    ],
    correctAnswer: "Snížení tlaku / přerušení techniky a slovnímu ověření komfortu a intenzity",
    explanationCs: "Bolestivá reakce zvyšuje svalový tonus a ztrácí terapeutický efekt. Proaktivní dotaz („Jak tlak?“) posiluje důvěru. Někteří klienti (zdvořilí, s traumatem) sami nepromluví – masér musí odhadnout z neverbálu.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.3 Komunikace během masáže`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "mc",
    stemCs: "Nezletilý klient (do 15 let) přichází na masáž bez doprovodu. Masér:",
    choices: [
      "Masíruje bez dotazu, stačí že přišel",
      "Odmítne ošetření, nezletilý potřebuje informovaný souhlas zákonného zástupce",
      "Pošle SMS rodiči a začne masáž",
      "Vyžádá si občanský průkaz",
    ],
    correctAnswer: "Odmítne ošetření, nezletilý potřebuje informovaný souhlas zákonného zástupce",
    explanationCs: "Podle § 31 občanského zákoníku (zpracování zdravotních údajů a zásah do tělesné integrity) potřebuje nezletilý u neléčebného zákroku typicky souhlas zákonného zástupce; u mladších dětí je jeho přítomnost obvykle nutná. Přísnější pravidla platí u dětí do 13 let podle GDPR pro zpracování dat.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.4; Zákon 89/2012 Sb. § 31, § 35; ${GDPR} čl. 8`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "open",
    stemCs: "Popište, jaké minimální informace by měl obsahovat vstupní dotazník (intake formulář) před první masáží. Uveďte alespoň 6 položek a u každé stručně zdůvodněte, proč je důležitá.",
    correctAnswer: "Příklady (stačí 6+): 1) Identifikační údaje (jméno, datum narození, kontakt) – pro vedení spisu a kontaktování. 2) Důvod návštěvy / očekávání – pro cílenou masáž. 3) Aktuální zdravotní stav, akutní obtíže, bolest – pro detekci akutní kontraindikace. 4) Chronická onemocnění (DM, hypertenze, onkologická anamnéza, srdeční choroby) – ovlivní techniku a mohou být kontraindikací. 5) Úrazy, operace, jizvy – bezpečnost, lokální kontraindikace. 6) Užívané léky (zejm. antikoagulancia, kortikoidy) – vliv na masáž. 7) Alergie (vč. olejů) – volba přípravku. 8) Těhotenství / kojení – poloha, hloubka. 9) Kožní onemocnění – lokální/celková kontraindikace. 10) Souhlas s masáží a se zpracováním osobních údajů (GDPR). 11) Kontakt v případě nouze.",
    explanationCs: "Dotazník slouží k bezpečnosti (detekce kontraindikací), individualizaci (přizpůsobení techniky) a právní ochraně (důkaz, že masér postupoval s péčí řádného odborníka). Podpis klienta + datum jsou nezbytné.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.2 Zdravotní anamnéza; ${CURRICULUM_D1}`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "open",
    stemCs: "Popište správný postup prvního kontaktu s klientem – od jeho příchodu do provozovny po začátek masáže.",
    correctAnswer: "1) Přivítání, představení, krátký small-talk pro snížení úzkosti. 2) Zkontrolovat rezervaci a identifikační údaje. 3) Pokud jde o novou návštěvu: vyplnění vstupního dotazníku a podpis souhlasů (masáž + GDPR). 4) Krátký rozhovor o cíli návštěvy, obtížích, očekáváních a případné změně od předchozí návštěvy. 5) Vysvětlit průběh masáže (délka, techniky, polohy, nutnost svléknutí, užití prostěradla/ručníku, stop-signál). 6) Vyhradit klientovi soukromí pro převlečení, opustit místnost. 7) Po vstupu zkontrolovat polohu klienta, přikrytí a teplotu, ověřit dotazem, zda je vše v pořádku. 8) Krátce zopakovat, co se bude dít jako první, a zeptat se na tlak/intenzitu po prvních dotazech.",
    explanationCs: "Struktura „uvítání → anamnéza → informovaný souhlas → vysvětlení → soukromí → kontrola komfortu“ buduje důvěru, snižuje úzkost a zajišťuje, že nedochází k nedorozumění ohledně nahoty, doteku a rozsahu masáže.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.3 Komunikační protokoly`,
  },
  {
    topicSlug: "komunikace-s-klientem",
    kind: "open",
    stemCs: "Jak byste přizpůsobili průběh masáže klientovi, který v anamnéze uvede výraznou úzkost nebo historii traumatu? Popište alespoň 5 konkrétních opatření.",
    correctAnswer: "1) Podrobné vysvětlení průběhu krok po kroku a získání opakovaného souhlasu. 2) Domluvený stop-signál (slovo nebo gesto) – klient může kdykoliv ukončit masáž bez omluvy. 3) Zvolit polohu, kterou si klient vybere (vleže na zádech místo na břiše, hlava viditelně vpřed). 4) Začít od vzdálenějších, méně citlivých oblastí (ruce, nohy) a postupovat směrem k trupu. 5) Ohlašovat každou novou oblast doteku předem. 6) Vyhnout se oblastem, kde klient vyjádřil nekomfort (krk, vnitřní strana stehen). 7) Udržovat klidnou, nízkou hlasitost hlasu; předvídatelné tempo a tlak. 8) Minimalizovat překvapivé pohyby; zvuk hudby a světla dohodnout předem. 9) Po masáži dát klientovi čas v klidu a nabídnout doprovod.",
    explanationCs: "Trauma-informovaný přístup sleduje 4 principy SAMHSA: bezpečí, důvěryhodnost/transparentnost, volba, spolupráce. Nejde o psychoterapii – masér nevyzvídá detaily traumatu, pouze respektuje hranice a dává kontrolu.",
    sourceRef: `${NSK_KOMUNIKACE} § 1.4 Speciální populace`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Za osobní údaj podle GDPR se považuje:",
    choices: [
      "Pouze rodné číslo a adresa",
      "Jakákoliv informace o identifikované nebo identifikovatelné fyzické osobě",
      "Pouze informace shromážděné online",
      "Pouze údaje, které klient označí jako citlivé",
    ],
    correctAnswer: "Jakákoliv informace o identifikované nebo identifikovatelné fyzické osobě",
    explanationCs: "GDPR čl. 4 bod 1 definuje osobní údaj velmi široce – jméno, e-mail, telefon, IP adresa, fotografie, zdravotní údaje. Identifikovatelnost může být i nepřímá (kombinace údajů).",
    sourceRef: `${GDPR} čl. 4 bod 1`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Údaje o zdravotním stavu klienta spadají podle GDPR do:",
    choices: [
      "Běžných osobních údajů",
      "Zvláštní kategorie osobních údajů („citlivé údaje“) s přísnějším režimem zpracování",
      "Veřejných údajů",
      "Statistických údajů bez ochrany",
    ],
    correctAnswer: "Zvláštní kategorie osobních údajů („citlivé údaje“) s přísnějším režimem zpracování",
    explanationCs: "Článek 9 GDPR zařazuje údaje o zdravotním stavu mezi zvláštní kategorii. Jejich zpracování je v zásadě zakázáno; masér je smí zpracovávat pouze na základě výslovného souhlasu klienta nebo jiného důvodu dle čl. 9 odst. 2.",
    sourceRef: `${GDPR} čl. 9`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Právním titulem pro zpracování zdravotních údajů klienta masérem (anamnéza, kontraindikace) je obvykle:",
    choices: [
      "Oprávněný zájem správce",
      "Výslovný (informovaný) souhlas klienta dle čl. 9 odst. 2 písm. a) GDPR",
      "Plnění smlouvy bez dalších požadavků",
      "Zákonná povinnost bez souhlasu",
    ],
    correctAnswer: "Výslovný (informovaný) souhlas klienta dle čl. 9 odst. 2 písm. a) GDPR",
    explanationCs: "Masér není poskytovatelem zdravotních služeb, nelze proto využít titul „poskytování zdravotní péče“ (čl. 9 odst. 2 písm. h)). Nejčistší titul je výslovný, svobodný a prokazatelný souhlas, který lze odvolat.",
    sourceRef: `${GDPR} čl. 9 odst. 2 písm. a); čl. 7`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Klient uplatní právo na výmaz („zapomenutí“) podle čl. 17 GDPR. Správný postup:",
    choices: [
      "Vše smazat okamžitě bez jakéhokoliv záznamu",
      "Žádost ignorovat",
      "Posoudit, které údaje lze smazat a které musí zůstat kvůli zákonné povinnosti (účetnictví, daně); smazat zbytek a žádost zdokumentovat; odpovědět klientovi do 1 měsíce",
      "Odpovědět klientovi, že výmaz není možný",
    ],
    correctAnswer: "Posoudit, které údaje lze smazat a které musí zůstat kvůli zákonné povinnosti (účetnictví, daně); smazat zbytek a žádost zdokumentovat; odpovědět klientovi do 1 měsíce",
    explanationCs: "Právo na výmaz není absolutní (čl. 17 odst. 3 GDPR) – lze odmítnout část výmazu, pokud zpracování je nutné k plnění zákonné povinnosti. Na žádost je nutno reagovat bez zbytečného odkladu, nejpozději do 1 měsíce (čl. 12 odst. 3).",
    sourceRef: `${GDPR} čl. 17, čl. 12`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Kdy je správce povinen ohlásit porušení zabezpečení osobních údajů (data breach) dozorovému úřadu (ÚOOÚ)?",
    choices: [
      "Nikdy, stačí informovat klienta",
      "Do 30 dnů od zjištění",
      "Bez zbytečného odkladu, nejpozději do 72 hodin od zjištění incidentu",
      "Pouze pokud klient výslovně zažádá",
    ],
    correctAnswer: "Bez zbytečného odkladu, nejpozději do 72 hodin od zjištění incidentu",
    explanationCs: "Článek 33 GDPR: ohlášení ÚOOÚ do 72 h. Výjimka pouze pokud je nepravděpodobné, že dojde k riziku pro práva subjektů. Při vysokém riziku je třeba informovat i dotčené klienty (čl. 34).",
    sourceRef: `${GDPR} čl. 33, 34`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Daňové doklady (příjmové pokladní doklady, faktury) musí podnikající masér v ČR archivovat:",
    choices: [
      "1 rok",
      "Minimálně 5 let (účetní zákon); u plátců DPH 10 let pro doklady k DPH",
      "Doživotně",
      "Žádná povinnost, doklady lze zničit po vystavení",
    ],
    correctAnswer: "Minimálně 5 let (účetní zákon); u plátců DPH 10 let pro doklady k DPH",
    explanationCs: "Zákon 563/1991 Sb. o účetnictví § 31 – účetní záznamy 5 let, účetní závěrky 10 let. Zákon 235/2004 Sb. § 35 – daňové doklady u DPH 10 let. Delší archivace slouží i jako obrana v občanskoprávním sporu (promlčecí lhůty).",
    sourceRef: `Zákon 563/1991 Sb. § 31; Zákon 235/2004 Sb. § 35`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Masér používá cloudový rezervační systém (mimo EU server) pro ukládání klientských dat a anamnézy. Správný postup z hlediska GDPR:",
    choices: [
      "Neřešit, klient o tom nemusí vědět",
      "Ověřit, že poskytovatel je zpracovatelem dle čl. 28 GDPR, uzavřít písemnou zpracovatelskou smlouvu, ošetřit mezinárodní přenos dat (SCC, adequacy decision) a informovat klienty v zásadách ochrany osobních údajů",
      "Data stačí ukládat v e-mailu",
      "Používat pouze systémy bez šifrování kvůli přehlednosti",
    ],
    correctAnswer: "Ověřit, že poskytovatel je zpracovatelem dle čl. 28 GDPR, uzavřít písemnou zpracovatelskou smlouvu, ošetřit mezinárodní přenos dat (SCC, adequacy decision) a informovat klienty v zásadách ochrany osobních údajů",
    explanationCs: "Čl. 28 vyžaduje písemnou smlouvu se zpracovatelem (DPA). Pro přenos do třetích zemí (mimo EHP) je třeba právní nástroj dle čl. 44–49 (standardní smluvní doložky, rozhodnutí o odpovídající úrovni ochrany). Informace o příjemcích údajů patří do privacy policy.",
    sourceRef: `${GDPR} čl. 28, čl. 44–49`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "mc",
    stemCs: "Masér chce posílat klientům newsletter s nabídkami. Potřebuje:",
    choices: [
      "Nic, stačí e-mail z klientské databáze",
      "Oddělený, prokazatelný souhlas klienta s možností kdykoliv se odhlásit (opt-out v každé zprávě)",
      "Pouze uvést do paty zprávy adresu provozovny",
      "Pouze nahlášení marketingu finančnímu úřadu",
    ],
    correctAnswer: "Oddělený, prokazatelný souhlas klienta s možností kdykoliv se odhlásit (opt-out v každé zprávě)",
    explanationCs: "Zákon 480/2004 Sb. § 7 (zákon o některých službách informační společnosti) vyžaduje souhlas před zasíláním obchodních sdělení, s možností bezplatného odhlášení. Souhlas musí být oddělen od souhlasu se zpracováním zdravotních údajů (GDPR čl. 7 odst. 2 – granularita souhlasu).",
    sourceRef: `Zákon 480/2004 Sb. § 7; ${GDPR} čl. 7`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "open",
    stemCs: "Vyjmenujte a stručně charakterizujte alespoň 6 práv subjektu údajů (klienta) podle GDPR.",
    correctAnswer: "1) Právo na informace (čl. 13, 14) – klient musí být informován, jaké údaje se zpracovávají, proč a jak dlouho. 2) Právo na přístup (čl. 15) – klient má nárok na kopii zpracovávaných údajů. 3) Právo na opravu (čl. 16) – opravit nepřesné údaje. 4) Právo na výmaz / „být zapomenut“ (čl. 17) – za splnění podmínek údaje smazat. 5) Právo na omezení zpracování (čl. 18) – dočasně zastavit zpracování. 6) Právo na přenositelnost (čl. 20) – získat údaje ve strukturovaném formátu a přenést jinam. 7) Právo vznést námitku (čl. 21). 8) Právo odvolat souhlas kdykoliv (čl. 7 odst. 3). 9) Právo podat stížnost u ÚOOÚ (čl. 77).",
    explanationCs: "Těchto 8+ práv tvoří jádro GDPR. Masér musí být schopen každé právo klientovi vyřídit do 1 měsíce (čl. 12 odst. 3), bezplatně (s výjimkou zjevně nedůvodných nebo nepřiměřených žádostí).",
    sourceRef: `${GDPR} čl. 13–22, 77`,
  },
  {
    topicSlug: "dokumentace-a-gdpr",
    kind: "open",
    stemCs: "Popište, jaké dokumenty tvoří kompletní klientský spis maséra a uveďte orientační doby archivace pro každou skupinu.",
    correctAnswer: "1) Vstupní dotazník / zdravotní anamnéza + informovaný souhlas s masáží a se zpracováním osobních údajů: uchovávat po dobu trvání vztahu s klientem + po dobu promlčecí lhůty (obvykle 3–10 let kvůli případné občanskoprávní odpovědnosti; § 629 OZ). 2) Záznamy o jednotlivých masážích (datum, typ, poznámky, nestandardní reakce): stejně jako anamnéza. 3) Účetní doklady (faktury, pokladní doklady, příjemky): 5 let dle zákona 563/1991 Sb. § 31. 4) Daňové doklady u plátců DPH: 10 let dle zákona 235/2004 Sb. § 35. 5) Souhlas s marketingem a záznamy o odhlášení: po dobu trvání souhlasu + prokazatelnost. 6) Záznamy o incidentech / stížnostech: minimálně 3 roky kvůli pojistné události. 7) Záznamy o činnostech zpracování (čl. 30 GDPR) – pokud je masér povinen je vést. Po uplynutí lhůty údaje bezpečně zlikvidovat (skartace, vymazání).",
    explanationCs: "Rozlišení lhůt: účetní × GDPR × občanskoprávní odpovědnost × marketing. Nejkratší lhůta obvykle postačí u marketingových souhlasů, nejdelší u daňových dokladů. Princip minimalizace (čl. 5 odst. 1 písm. c GDPR) – nezpracovávat déle, než je nutné.",
    sourceRef: `${GDPR} čl. 5, 30; Zákon 563/1991 Sb. § 31; Zákon 235/2004 Sb. § 35; Zákon 89/2012 Sb. § 629`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Mezi úrovně ošetření nástrojů a pomůcek podle Spauldingovy klasifikace patří:",
    choices: [
      "Pouze mytí teplou vodou",
      "Dekontaminace, dezinfekce (vysoká / střední / nízká) a sterilizace podle kategorie pomůcky",
      "Pouze UV záření",
      "Pouze pračka na 40 °C",
    ],
    correctAnswer: "Dekontaminace, dezinfekce (vysoká / střední / nízká) a sterilizace podle kategorie pomůcky",
    explanationCs: "Spauldingova klasifikace dělí pomůcky na kritické (pronikají do sterilních tkání – sterilizace), semikritické (kontakt se sliznicí/porušenou kůží – vysoký stupeň dezinfekce) a nekritické (kontakt pouze s neporušenou kůží – dezinfekce nízkého / středního stupně). Masérské stoly a lehátka patří mezi nekritické povrchy.",
    sourceRef: `${NSK_HYGIENA} § 3.2 Dezinfekce pomůcek; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Mezi tři hlavní skupiny metod dezinfekce patří:",
    choices: [
      "Fyzikální, chemická, kombinovaná (fyzikálně-chemická)",
      "Manuální, strojní, automatická",
      "Denní, týdenní, měsíční",
      "Klientská, zaměstnanecká, veřejná",
    ],
    correctAnswer: "Fyzikální, chemická, kombinovaná (fyzikálně-chemická)",
    explanationCs: "Fyzikální dezinfekce využívá teplo (var, suchý žár), UV záření, filtraci. Chemická používá dezinfekční přípravky (alkoholy, chlornany, aldehydy, peroxidy, kvartérní amoniové sloučeniny). Kombinovaná je oba způsoby (např. mycí-dezinfekční automat).",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Proč se dezinfekční roztoky ředí přesně podle návodu výrobce a nepoužívají se „silnější“?",
    choices: [
      "Vyšší koncentrace vždy zvyšuje účinnost bez rizika",
      "Přesná koncentrace garantuje účinnost i bezpečnost; vyšší koncentrace zvyšuje toxicitu, dráždivost a může poškodit povrch; nižší je neúčinná",
      "Pro úsporu je lepší ředit na polovinu",
      "Koncentrace nemá vliv na výsledek",
    ],
    correctAnswer: "Přesná koncentrace garantuje účinnost i bezpečnost; vyšší koncentrace zvyšuje toxicitu, dráždivost a může poškodit povrch; nižší je neúčinná",
    explanationCs: "Výrobce testuje účinnost pro danou koncentraci a expoziční dobu (tzv. spektrum dle ČSN EN). Příliš silný roztok riskuje alergické reakce, korozi a zdravotní škody; slabý vytvoří falešný pocit bezpečí, ale mikroby přežijí.",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Masážní stůl (lehátko) by měl být mezi klienty ošetřen:",
    choices: [
      "Pouze vyměnou prostěradla",
      "Vyměnou textilie + otřením povrchů dezinfekčním přípravkem s plochovou účinností na baktérie a viry, dodržením doby expozice podle návodu",
      "Dezinfekcí jednou týdně",
      "Vodou a mýdlem",
    ],
    correctAnswer: "Vyměnou textilie + otřením povrchů dezinfekčním přípravkem s plochovou účinností na baktérie a viry, dodržením doby expozice podle návodu",
    explanationCs: "Mezi každým klientem se textilie (prostěradlo, ručník) vyměňují. Povrchy stolu, opěrky hlavy, područky se otírají prostředkem se schváleným spektrem (bakterie včetně tuberkulózy, viry, plísně), doba expozice je 1–5 minut dle výrobku. Zasychání spreje bez setření neodpovídá protokolu.",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Hygienická dezinfekce rukou (rub rukou + dlaně + prsty + palce + nehtová lůžka) trvá minimálně:",
    choices: [
      "10 sekund",
      "20 sekund pouhé opláchnutí vodou",
      "30 sekund intenzivního vtírání alkoholového přípravku až do zaschnutí (min. 3 ml)",
      "5 minut",
    ],
    correctAnswer: "30 sekund intenzivního vtírání alkoholového přípravku až do zaschnutí (min. 3 ml)",
    explanationCs: "Podle ČSN EN 1500 je hygienická dezinfekce rukou definována jako vtírání alkoholového dezinfekčního přípravku (obvykle 60–80% etanol/isopropanol) po dobu minimálně 30 s v sedmi krocích, až do zaschnutí. Před tím je nutné mechanické umytí rukou mýdlem, jsou-li viditelně znečištěné.",
    sourceRef: `${NSK_HYGIENA} § 3.3 Hygiena rukou; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Při nošení jednorázových rukavic masér:",
    choices: [
      "Může je mezi klienty pouze otřít dezinfekcí",
      "Používá je namísto mytí rukou, mytí rukou už není nutné",
      "Nasadí je až po hygienické dezinfekci rukou, po použití je sejme správnou technikou bez dotyku s kontaminovanou plochou a ruce opět dezinfikuje",
      "Používá je pouze při kontaktu s obličejem",
    ],
    correctAnswer: "Nasadí je až po hygienické dezinfekci rukou, po použití je sejme správnou technikou bez dotyku s kontaminovanou plochou a ruce opět dezinfikuje",
    explanationCs: "Rukavice nenahrazují hygienu rukou. Mají se měnit mezi klienty, při poškození a při přechodu z „špinavé“ na „čistou“ činnost. Sundávání „obráceným rukávem“ brání kontaminaci kůže.",
    sourceRef: `${NSK_HYGIENA} § 3.3 PPE; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Použité prostěradlo / ručník od klienta masér:",
    choices: [
      "Složí a použije pro dalšího klienta, pokud vypadá čistě",
      "Uloží do uzavíratelného označeného koše na špinavé prádlo a vypere při teplotě min. 60 °C (ideálně 90 °C) s dezinfekčním přídavkem",
      "Okamžitě roztřepá v provozovně",
      "Odloží volně vedle lehátka",
    ],
    correctAnswer: "Uloží do uzavíratelného označeného koše na špinavé prádlo a vypere při teplotě min. 60 °C (ideálně 90 °C) s dezinfekčním přídavkem",
    explanationCs: "Uzavřený koš brání aerosolizaci mikrobů. Praní ≥ 60 °C inaktivuje většinu běžných patogenů; u ručníků z oblasti nohou (mykózy) a viditelně znečištěných prádel se volí 90 °C s dezinfekčním přídavkem. Třepání šíří kontaminaci do vzduchu.",
    sourceRef: `${NSK_HYGIENA} § 3.2 Prádlo; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Z hlediska ochrany proti mykózám a plísním je mezi klienty nejdůležitější:",
    choices: [
      "Omývat stůl vodou",
      "Vyměnit textilie a dezinfikovat oblast, kde byla chodidla / nohy klienta, přípravkem s fungicidním účinkem",
      "Pouze vyvětrat místnost",
      "Nic, mykózy se masáží nepřenášejí",
    ],
    correctAnswer: "Vyměnit textilie a dezinfikovat oblast, kde byla chodidla / nohy klienta, přípravkem s fungicidním účinkem",
    explanationCs: "Tinea pedis / onychomykóza se přenáší velmi snadno přímým kontaktem i přes textilii a povrchy. Pro ochranu dalších klientů i maséra je nutné použít dezinfekci s certifikovaným fungicidním účinkem a nepoužívat stejnou textilii opakovaně.",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Při použití masážního oleje z většího rezervoáru masér:",
    choices: [
      "Namáčí celou ruku přímo do lahve",
      "Odlévá olej do jednorázové (nebo dezinfikované) misky / dávkovače a k jednomu klientovi používá odděleně, zbytek nevrací zpět",
      "Používá jednu lahev celý měsíc bez omezení",
      "Směšuje oleje všech klientů dohromady",
    ],
    correctAnswer: "Odlévá olej do jednorázové (nebo dezinfikované) misky / dávkovače a k jednomu klientovi používá odděleně, zbytek nevrací zpět",
    explanationCs: "Aplikační nádoba musí bránit křížové kontaminaci – olej kontaminovaný kůží jednoho klienta se nesmí dostat k dalšímu. Dávkovače s pumpičkou nebo jednorázové nádobky jsou standard. Vracení přebytků zpět je hrubé porušení hygieny.",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Masér má akutní virózu s horečkou, kašlem a rýmou. Jeho povinnost:",
    choices: [
      "Přijít do práce v respirátoru a masírovat dál",
      "Přerušit práci, nahlásit nemoc, nevracet se dokud je infekční – zpravidla bez teploty min. 48 h a po konzultaci s lékařem",
      "Masírovat jen zdravé mladé klienty",
      "Přesunout klienty k jinému masérovi bez omluvy",
    ],
    correctAnswer: "Přerušit práci, nahlásit nemoc, nevracet se dokud je infekční – zpravidla bez teploty min. 48 h a po konzultaci s lékařem",
    explanationCs: "§ 20 zákona 258/2000 Sb. ukládá osobám vykonávajícím epidemiologicky významnou činnost nevykonávat ji při infekčním onemocnění. Přerušení je zároveň ochrana klientů (zejm. imunokompromitovaných).",
    sourceRef: `${NSK_HYGIENA} § 3.3 Nemoc; ${ZAKON_258} § 20`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Osoba vykonávající epidemiologicky významnou činnost (včetně maséra) musí být v ČR zdravotně prohlédnuta:",
    choices: [
      "Jednorázově při zahájení živnosti, pak už nikdy",
      "Před zahájením činnosti (vstupní prohlídka) a poté pravidelně podle vyhlášky 79/2013 Sb. – obvykle jednou za několik let u kategorie 1, ve vyšších kategoriích častěji; mimořádně při podezření na infekci",
      "Pouze pokud o to klient požádá",
      "Jednou za 20 let",
    ],
    correctAnswer: "Před zahájením činnosti (vstupní prohlídka) a poté pravidelně podle vyhlášky 79/2013 Sb. – obvykle jednou za několik let u kategorie 1, ve vyšších kategoriích častěji; mimořádně při podezření na infekci",
    explanationCs: "Pracovnělékařské prohlídky u zaměstnanců / OSVČ ve vazbě na kategorizaci prací (vyhl. 79/2013 Sb.). Dokumentaci (potvrzení o zdravotní způsobilosti) uchovává provozovatel a při kontrole předkládá KHS.",
    sourceRef: `${NSK_HYGIENA} § 3.5; ${VYHL_306}; vyhláška 79/2013 Sb.`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "mc",
    stemCs: "Dojde-li při masáži k poranění maséra jehlou / předmětem, který byl v kontaktu s krví klienta (vpich, pořezání):",
    choices: [
      "Nic neřešit",
      "Místo vymačkat, opláchnout tekoucí vodou s mýdlem, desinfikovat (nedráždivě), vyhledat lékařskou péči do 2 h kvůli post-expoziční profylaxi, incident písemně zaznamenat a nahlásit zaměstnavateli / pojišťovně",
      "Zatáhnout tlakovým obvazem a pokračovat",
      "Hlásit až za týden",
    ],
    correctAnswer: "Místo vymačkat, opláchnout tekoucí vodou s mýdlem, desinfikovat (nedráždivě), vyhledat lékařskou péči do 2 h kvůli post-expoziční profylaxi, incident písemně zaznamenat a nahlásit zaměstnavateli / pojišťovně",
    explanationCs: "Standardní postup při biologické expozici (HBV, HCV, HIV). Čas do 2 h je důležitý pro rozhodnutí o PEP (post-expoziční profylaxi HIV). Dokumentace incidentu v provozní knize je povinností podle provozního (operačního) řádu.",
    sourceRef: `${NSK_HYGIENA} § 3.4 Incidenty; ${VYHL_306}; ${ZAKON_258}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "open",
    stemCs: "Popište postup (kroky) standardní hygieny rukou v masérské provozovně – co kdy a jak.",
    correctAnswer: "1) Mechanické umytí rukou – studenou/vlažnou vodou a mýdlem po dobu cca 30–60 s, pokud jsou ruce viditelně znečištěné nebo po záchodě / jídle / přestávce. 2) Hygienická dezinfekce rukou – alkoholovým přípravkem 60–80 % cca 3 ml, vtírat po celém povrchu rukou (dlaně, rub, meziprstí, palce, nehtová lůžka, zápěstí) min. 30 s v 7 krocích podle ČSN EN 1500, až do zaschnutí. 3) Provádí se: před a po každém klientovi, před nasazením rukavic a po jejich sundání, po jakémkoliv kontaktu s biologickým materiálem a po čištění provozovny. 4) Pozor na dlouhé nehty, šperky, prsteny, odlupování laku – vylučují správnou hygienu. 5) Péče o kůži rukou (reparační krém) po skončení směny – zabrání prasklinám, které jsou branou infekce.",
    explanationCs: "Dodržování hygieny rukou je klíčové opatření ochrany před přenosem infekcí v masáži. Alkoholová dezinfekce rukou je ve většině případů efektivnější než mytí vodou a mýdlem; mytí je ale nutné při viditelném znečištění a pro odstranění spor (ty alkohol nezabije).",
    sourceRef: `${NSK_HYGIENA} § 3.3 Hygiena rukou; ${VYHL_306}; ČSN EN 1500`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "open",
    stemCs: "Popište kompletní postup ošetření masážního stolu a pomůcek mezi dvěma klienty.",
    correctAnswer: "1) Odstranit veškerou textilii (prostěradlo, ručník, polštářky potahy) a uložit do uzavřeného koše na špinavé prádlo. 2) Viditelné nečistoty (olej, pot) mechanicky odstranit jednorázovou papírovou utěrkou. 3) Otřít všechny plochy, kterých se klient dotkl (podložka, opěrka hlavy, područky, držák na obličej, nohy lehátka) dezinfekčním přípravkem se spektrem účinnosti na bakterie vč. mykobakterií, viry a plísně; dodržet kontaktní dobu uvedenou výrobcem (1–5 min). 4) Nevracet olej z použité misky do lahve; misku dezinfikovat nebo vyhodit (jednorázové). 5) Vyměnit dávkovač papírových ručníků / toaletního papíru v odkládací místnosti, je-li prázdný. 6) Vyhodit jednorázové rukavice, provést hygienickou dezinfekci vlastních rukou. 7) Nasadit čerstvé prostěradlo a přikrývku pro dalšího klienta. 8) Vyvětrat nebo použít vzduchotechniku (min. 5 min). 9) Zaznamenat úklid v provozní knize (datum, čas, přípravek, pracovník), pokud to provozní řád vyžaduje.",
    explanationCs: "Protokol odpovídá požadavkům operačního řádu schvalovaného KHS a vyhlášky 306/2012. Důraz je na čas expozice dezinfekce – zkrácený čas = neúčinné ošetření.",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}; ${ZAKON_258}`,
  },
  {
    topicSlug: "hygiena-a-dezinfekce",
    kind: "open",
    stemCs: "Vysvětlete rozdíl mezi sanitací, dezinfekcí a sterilizací a uveďte, do které kategorie spadá typická masérská provozovna.",
    correctAnswer: "Sanitace (čištění) – mechanické odstranění nečistot, biologického materiálu a části mikrobů vodou, saponátem a mechanickou silou; sama o sobě mikroby nezabíjí, je ale nezbytným prvním krokem. Dezinfekce – cílené usmrcení nebo inaktivace vegetativních forem mikroorganismů na neživých površích na akceptovatelnou úroveň (nikoli spor). Používá se na kůži (hygienická dezinfekce rukou), na povrchy (plochová) a na nástroje (vyšší / vysoký stupeň). Sterilizace – úplné usmrcení všech mikroorganismů včetně spor (autokláv, plazma, etylenoxid). Typická masérská provozovna vystačí se sanitací + dezinfekcí (nekritické povrchy). Sterilizace je potřebná pouze u případných nástrojů pronikajících přes kůži – ty ale masér zpravidla nepoužívá (patří do zdravotnictví).",
    explanationCs: "Znalost hierarchie je klíčová pro volbu přípravků a pro komunikaci s KHS. Záměna pojmů vede buď k nedostatečné ochraně (např. „otřu to mýdlem“), nebo k zbytečným nákladům (sterilizace lehátka).",
    sourceRef: `${NSK_HYGIENA} § 3.2; ${VYHL_306}`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Masérská služba je podle zákona č. 258/2000 Sb. klasifikována jako:",
    choices: [
      "Běžná živnost bez zvláštních požadavků",
      "Epidemiologicky významná činnost s povinností schváleného provozního (operačního) řádu",
      "Zdravotní služba dle zákona 372/2011 Sb.",
      "Výrobní činnost",
    ],
    correctAnswer: "Epidemiologicky významná činnost s povinností schváleného provozního (operačního) řádu",
    explanationCs: "Masáž spadá pod § 19–22 zákona 258/2000 Sb. (epidemiologicky významné činnosti – kontakt s obnaženými částmi těla). Provozovatel musí vypracovat provozní (operační) řád a nechat jej schválit krajskou hygienickou stanicí (KHS) před zahájením činnosti.",
    sourceRef: `${NSK_HYGIENA} § 3.4; ${ZAKON_258} § 19–22`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Provozní (operační) řád masérské provozovny schvaluje:",
    choices: [
      "Obecní úřad",
      "Krajská hygienická stanice (KHS) místně příslušná provozovně",
      "Živnostenský úřad",
      "Hasičský záchranný sbor",
    ],
    correctAnswer: "Krajská hygienická stanice (KHS) místně příslušná provozovně",
    explanationCs: "KHS je dozorový orgán ochrany veřejného zdraví. Provozní řád obsahuje popis provozovny, úklidové a dezinfekční postupy, nakládání s prádlem, režim pomůcek, zacházení s odpady, postupy při incidentech a havarijní plán. Bez schválení nelze provoz zahájit.",
    sourceRef: `${NSK_HYGIENA} § 3.4; ${ZAKON_258}`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Mezi povinné údaje provozního (operačního) řádu masérské provozovny obvykle patří:",
    choices: [
      "Pouze otevírací doba",
      "Popis provozovny a činností, režim úklidu a dezinfekce, nakládání s prádlem, pomůckami a odpady, postupy při incidentech, pitná voda a vzduchotechnika, zdravotní způsobilost pracovníků",
      "Soupis hudebních skladeb pouštěných klientům",
      "Seznam nejprodávanějších produktů",
    ],
    correctAnswer: "Popis provozovny a činností, režim úklidu a dezinfekce, nakládání s prádlem, pomůckami a odpady, postupy při incidentech, pitná voda a vzduchotechnika, zdravotní způsobilost pracovníků",
    explanationCs: "Obsah provozního řádu vychází z § 21 zákona 258/2000 Sb. a metodiky KHS. Řád musí odrážet reálný provoz – kopírovat vzor z internetu bez úprav je při kontrole riskantní.",
    sourceRef: `${NSK_HYGIENA} § 3.4; ${ZAKON_258} § 21`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Minimální plocha masážní místnosti pro jedno pracovní místo se podle orientačních hygienických požadavků uvádí:",
    choices: [
      "Cca 8 m²",
      "Cca 24 m² (bývá uváděno jako orientační minimum pro komfortní provoz; přesnost vždy ověřit s KHS)",
      "Cca 100 m²",
      "Neexistuje žádná hranice",
    ],
    correctAnswer: "Cca 24 m² (bývá uváděno jako orientační minimum pro komfortní provoz; přesnost vždy ověřit s KHS)",
    explanationCs: "Konkrétní plošný požadavek je historicky cca 24 m² na pracovní místo (aby se vešlo lehátko + pracovní prostor + místo pro klienta na převlečení). Aktuální metodika KHS se může lišit podle regionu, proto se vždy ověřuje před otevřením.",
    sourceRef: `${NSK_HYGIENA} § 3.1 Prostory; ${CURRICULUM_D3}`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Masérská provozovna musí mít zajištěno:",
    choices: [
      "Pouze pitnou vodu z kohoutku",
      "Tekoucí pitnou teplou a studenou vodu, oddělené místo pro mytí rukou personálu, WC pro klienty, větrání odpovídající provozu, osvětlení odpovídající činnosti",
      "Pouze dezinfekci rukou",
      "Jen toalety pro zaměstnance",
    ],
    correctAnswer: "Tekoucí pitnou teplou a studenou vodu, oddělené místo pro mytí rukou personálu, WC pro klienty, větrání odpovídající provozu, osvětlení odpovídající činnosti",
    explanationCs: "Základní vybavení podle vyhl. 306/2012 a metodiky KHS: dostatek vody, umyvadla v pracovní místnosti, oddělené skladování čistého a špinavého prádla, WC dostupné klientům, dostatečné větrání (přirozené / vzduchotechnika) a osvětlení. Chybějící umyvadlo přímo v masážní místnosti je typickým důvodem neschválení provozu.",
    sourceRef: `${NSK_HYGIENA} § 3.1; ${VYHL_306}`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Čisté a použité (špinavé) prádlo se v provozovně:",
    choices: [
      "Skladuje společně v jednom koši",
      "Skladuje odděleně – čisté v uzavřených uzamykatelných skříních / boxech, špinavé v uzavíratelných koších, aby nedocházelo ke křížové kontaminaci",
      "Ukládá na lehátko",
      "Pere u klienta doma",
    ],
    correctAnswer: "Skladuje odděleně – čisté v uzavřených uzamykatelných skříních / boxech, špinavé v uzavíratelných koších, aby nedocházelo ke křížové kontaminaci",
    explanationCs: "Oddělený režim čistého a použitého prádla je základní princip bariérové ochrany. Při kontrole KHS sleduje, zda není skříň s čistým prádlem ve stejné místnosti jako koš se špinavým, zda jsou označené a zda je špinavé prádlo přepravováno v uzavřených obalech.",
    sourceRef: `${NSK_HYGIENA} § 3.2 Prádlo; ${VYHL_306}`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Masérský odpad (použité jednorázové rukavice, papírové utěrky kontaminované potem / olejem) patří do kategorie:",
    choices: [
      "Nebezpečný zdravotnický odpad (žlutý pytel, spálení ve speciálním zařízení) ve všech případech",
      "Běžný komunální odpad, pokud není kontaminován krví / biologickým materiálem; při kontaminaci krví se třídí jako nebezpečný odpad a likviduje podle zákona č. 541/2020 Sb.",
      "Nebezpečný chemický odpad",
      "Recyklovatelný plast bez výjimky",
    ],
    correctAnswer: "Běžný komunální odpad, pokud není kontaminován krví / biologickým materiálem; při kontaminaci krví se třídí jako nebezpečný odpad a likviduje podle zákona č. 541/2020 Sb.",
    explanationCs: "Pokud při masáži nedojde ke kontaktu s krví (masér nenarušuje kůži), odpad jde do běžného komunálu. V případě úrazu nebo péče o otevřenou ranku je povinnost oddělit do označeného kontejneru a zajistit odbornou likvidaci.",
    sourceRef: `${NSK_HYGIENA} § 3.1 Odpady; zákon 541/2020 Sb. o odpadech`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "mc",
    stemCs: "Kontrola KHS ohlášená / neohlášená v provozovně. Provozovatel:",
    choices: [
      "Může kontrolu odmítnout",
      "Musí kontrolu strpět, předložit provozní řád, zdravotní průkazy, záznamy o dezinfekci, kategorie prací, informovat pracovníky; na zápis z kontroly může podat námitky do 15 dnů",
      "Musí zaplatit inspektorovi",
      "Kontrolu odloží na později",
    ],
    correctAnswer: "Musí kontrolu strpět, předložit provozní řád, zdravotní průkazy, záznamy o dezinfekci, kategorie prací, informovat pracovníky; na zápis z kontroly může podat námitky do 15 dnů",
    explanationCs: "Kontrola probíhá podle zákona č. 255/2012 Sb. o kontrole (kontrolní řád) a zákona 258/2000 Sb. Pracovník KHS se prokazuje služebním průkazem. Neumožnění kontroly je přestupek s vysokou pokutou. Povinná součinnost neznamená vydat se napospas – proti zápisu lze podat námitky a následně odvolání.",
    sourceRef: `${NSK_HYGIENA} § 3.4; ${ZAKON_258}; zákon 255/2012 Sb.`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "open",
    stemCs: "Popište, co musí obsahovat provozní (operační) řád masérské provozovny. Uveďte alespoň 7 oblastí.",
    correctAnswer: "1) Identifikace provozovatele a provozovny (adresa, IČO, odpovědná osoba). 2) Popis poskytovaných služeb (druh masáže, cílová klientela). 3) Plán a popis prostor (nákresek, plocha, vybavení, umyvadla, sociální zařízení). 4) Režim úklidu a dezinfekce (denní / týdenní / měsíční, použité přípravky, doba expozice, kdo provádí). 5) Nakládání s prádlem (druh, výměna mezi klienty, teplota praní, přeprava). 6) Nakládání s pomůckami (jednorázové × vícepoužitelné, postup dezinfekce / sterilizace). 7) Osobní a pracovní hygiena personálu (hygiena rukou, ochranné pomůcky, dress code). 8) Zdravotní způsobilost pracovníků (vstupní a pravidelné prohlídky, dokumentace). 9) Postupy při incidentech (poranění, biologická expozice, podezření na infekční onemocnění u klienta). 10) Nakládání s odpadem (tříděný komunální, nebezpečný). 11) Zásobování vodou, větrání, osvětlení. 12) Školení zaměstnanců a záznamy z něj. 13) Kontakty na KHS a lékaře pracovnělékařské služby.",
    explanationCs: "Obsah je definován § 21 zákona 258/2000 Sb. a metodikou KHS. Provozní řád musí být pravidelně aktualizován (změna prostor, služeb, pracovníků, dezinfekčních prostředků) a k dispozici při kontrole v tištěné podobě.",
    sourceRef: `${NSK_HYGIENA} § 3.4 Provozní řád; ${ZAKON_258} § 21; ${VYHL_306}`,
  },
  {
    topicSlug: "provozni-standardy",
    kind: "open",
    stemCs: "Jaké dokumenty by měla mít masérská provozovna kdykoliv k dispozici pro případ kontroly KHS?",
    correctAnswer: "1) Schválený provozní (operační) řád a doklad o jeho schválení KHS. 2) Živnostenské oprávnění na vázanou živnost „Masérské, rekondiční a regenerační služby“. 3) Osvědčení o profesní kvalifikaci (NSK 69-037-M nebo ekvivalent) pro každého maséra. 4) Platné potvrzení o zdravotní způsobilosti od poskytovatele pracovnělékařských služeb pro každého pracovníka (zdravotní průkaz). 5) Kategorizaci prací (§ 37 zákona 258/2000 Sb.). 6) Dokumentaci o školení BOZP, požární ochraně a školení k hygienickému režimu. 7) Bezpečnostní listy (SDS) používaných dezinfekčních přípravků a kosmetiky. 8) Záznamy o úklidu / dezinfekci (provozní kniha). 9) Záznamy o incidentech (úrazová kniha). 10) Nájemní smlouva / vlastnický doklad k prostorám, kolaudační souhlas k účelu užívání. 11) Souhlas se zpracováním osobních údajů klientů (GDPR) a záznamy o činnostech zpracování. 12) Smlouvu s dodavatelem likvidace nebezpečného odpadu, pokud je relevantní.",
    explanationCs: "Kontrola začíná zpravidla požadavkem na provozní řád a zdravotní průkazy; chybějící dokument = sankce. Udržování aktuální složky na viditelném místě a její pravidelná revize jsou součástí běžné provozní hygieny.",
    sourceRef: `${NSK_HYGIENA} § 3.4; ${ZAKON_258}; ${VYHL_306}`,
  },
];

async function main() {
  for (const t of topics) {
    await prisma.topic.upsert({
      where: { slug: t.slug },
      update: { nameCs: t.nameCs, weight: t.weight },
      create: t,
    });
  }

  const topicRecords = await prisma.topic.findMany({
    where: { slug: { in: topics.map((t) => t.slug) } },
  });
  const topicIdBySlug: Record<string, string> = Object.fromEntries(
    topicRecords.map((t) => [t.slug, t.id]),
  );

  await prisma.question.deleteMany({
    where: { topicId: { in: Object.values(topicIdBySlug) } },
  });

  for (const q of questions) {
    await prisma.question.create({
      data: {
        topicId: topicIdBySlug[q.topicSlug],
        kind: q.kind,
        stemCs: q.stemCs,
        choices: q.choices ? JSON.stringify(q.choices) : null,
        correctAnswer: q.correctAnswer,
        explanationCs: q.explanationCs,
        sourceRef: q.sourceRef,
      },
    });
  }

  const counts = await prisma.question.groupBy({
    by: ["topicId"],
    _count: { _all: true },
  });
  const nameById = Object.fromEntries(topicRecords.map((t) => [t.id, t.nameCs]));
  for (const c of counts) {
    console.log(`${nameById[c.topicId]}: ${c._count._all} questions`);
  }
  console.log(`Total seeded: ${questions.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
